# Generated by Django 4.2.4 on 2023-08-05 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=1000)),
                ('Poster', models.URLField(max_length=500)),
                ('Year', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'imdb')},
            },
        ),
        migrations.CreateModel(
            name='PrivateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=1000)),
                ('Poster', models.URLField(max_length=500)),
                ('Year', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'imdb')},
            },
        ),
    ]
